[toolchain]
anchor_version = "0.31.0"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
plotly = "FQH8xLxebgWgTkxhyWDSfb4b68ZoW1newgSKMNXgQj4c"

[programs.localnet]
plotly = "FQH8xLxebgWgTkxhyWDSfb4b68ZoW1newgSKMNXgQj4c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest  --runInBand"
print = "../node_modules/.bin/ts-node ./scripts/print.ts"
buyPlot = "../node_modules/.bin/ts-node ./scripts/buyPlot.ts"
otherUser = "ANCHOR_WALLET=./localnet/testUser.json ../node_modules/.bin/ts-node ./scripts/otherUser.ts"


[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
